version: '3'

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./ops/mysql:/docker-entrypoint-initdb.d"
      - ./var/mysql:/var/lib/mysql

  nginx:
    image: nginx:1.21
    ports:
      - "8080:80"
    volumes:
      - ./www/html:/code
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links: [php]

  php:
    build: ./ops/php-fpm
    image: rendimiento-php:latest
    container_name: php
    volumes:
      - ./www/html:/code

  redis:
    image: redis:7.0.0
    ports:
      - "6379:6379"
    volumes:
      - ./ops/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./var/redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  rabbitmq:
    image: rabbitmq:3.9.17-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - ./var/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
    ports:
      - "15672:15672"
      - "5672:5672"

  blackfire:
    image: blackfire/blackfire:2
    ports: ["8307"]
    environment:
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    user: root
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TAKE_FILE_OWNERSHIP=1"
    volumes:
      - ./var/elasticsearch/data:/usr/share/elasticsearch/data
      - ./ops/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
